[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This copies the assets folder to the output directory
[[plugins]]
  package = "netlify-plugin-copy"
  
  [plugins.inputs]
    contents = [
      { "source" = "public/assets", "target" = "dist/assets" }
    ]